version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.6
  test:
    # ref: https://github.com/ganta/git-orb/blob/master/.circleci/config.yml
    # Workaround for passing a SSH key with orb-tools/local-test-build command
    # https://github.com/CircleCI-Public/orb-tools-orb/blob/330d11bb0cdef3c2f24cb4e2c595ca01e55bfd8c/src/%40orb.yml#L107-L134
    commands:
      local-test-build:
        parameters:
          path:
            type: string
        steps:
          - run: cp << parameters.path >> tmp-config-src/config.yml
          - run: mkdir -pv $(dirname tmp-config-src.yml)
          - run: circleci config pack tmp-config-src > uncompiled-config.yml
          - run: cat uncompiled-config.yml
          - run: circleci config process uncompiled-config.yml > config.yml
          # Cannot access "~/.ssh" from working directory.
          # pass spin up env's CIRCLE_TAG to local circleci command.
          - run:
              command: |
                cp ~/.ssh/id_rsa ./id_rsa
                circleci local execute --checkout-key ./id_rsa -c config.yml -e CIRCLE_TAG=${CIRCLE_TAG} | \
                  tee local_build_output.txt /dev/stderr | \
                  tail -n 1 | \
                  grep "Success"

# yaml anchor filters
integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

prod-deploy_requires: &prod-deploy_requires [test-commands-master]

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: guitarrapc/git-shallow-clone
          requires:
            - orb-tools/pack
          filters:
            branches:
              ignore:
                - /^pull\/.*/
      - orb-tools/trigger-integration-workflow:
          ssh-fingerprints: 47:ab:89:32:ac:86:9e:37:0b:bf:b8:a0:d6:da:9e:3b
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore:
                - master
                - /pull.*/
      - orb-tools/trigger-integration-workflow:
          ssh-fingerprints: 47:ab:89:32:ac:86:9e:37:0b:bf:b8:a0:d6:da:9e:3b
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master

  integration-tests_prod-release:
    jobs:
      - orb-tools/pack:
          name: pack-dev
          filters: *integration-dev_filters
      - orb-tools/test-in-builds:
          attach-workspace: true
          orb-name: git-shallow-clone
          test-steps:
            # - test/local-test-build:
            #     path: tests/alpine_test_noopenssh.yml
            # - test/local-test-build:
            #     path: tests/alpine_test.yml
            - test/local-test-build:
                path: tests/basic_test.yml
            - test/local-test-build:
                path: tests/change_depth.yml
            - test/local-test-build:
                path: tests/change_fetchdepth.yml
            - test/local-test-build:
                path: tests/change_path.yml
            - test/local-test-build:
                path: tests/enable_github_keyscan.yml
            - test/local-test-build:
                path: tests/enable_bitbucket_keyscan.yml
          name: test-commands-dev
          filters: *integration-dev_filters
          requires:
            - pack-dev
      - orb-tools/pack:
          name: pack-master
          filters: *integration-master_filters
      - orb-tools/test-in-builds:
          attach-workspace: true
          orb-name: git-shallow-clone
          test-steps:
            - test/local-test-build:
                path: tests/alpine_test_noopenssh.yml
            - test/local-test-build:
                path: tests/alpine_test.yml
            - test/local-test-build:
                path: tests/basic_test.yml
            - test/local-test-build:
                path: tests/change_depth.yml
            - test/local-test-build:
                path: tests/change_fetchdepth.yml
            - test/local-test-build:
                path: tests/change_path.yml
            - test/local-test-build:
                path: tests/enable_github_keyscan.yml
            - test/local-test-build:
                path: tests/enable_bitbucket_keyscan.yml
          name: test-commands-master
          filters: *integration-master_filters
          requires:
            - pack-master
      # patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          orb-name: guitarrapc/git-shallow-clone
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/
      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          orb-name: guitarrapc/git-shallow-clone
          release: minor
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/
      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          orb-name: guitarrapc/git-shallow-clone
          release: major
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
