version: 2.1

orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@dev:alpha
  orb-tools: circleci/orb-tools@10.0.5

# Pipeline Parameters
## These parameters are used internally by orb-tools. Skip to the Jobs section.
parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

jobs:
  # Define one or more jobs which will utilize your orb's commands and parameters to validate your changes.
  integration-test-checkout:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout
  integration-test-checkout_advanced:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout_advanced
  integration-test-checkout_advanced_fetchoptions:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout_advanced:
          clone_options: '--shallow-since "5 days ago"'
          fetch_options: '--shallow-since "5 days ago"'
  integration-test-checkout_advanced_notags:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout_advanced:
          clone_options: "--depth 1"
          fetch_options: "--depth 1000 --no-tags"
          tag_fetch_options: "--no-tags"
      # should be no tags
      - run: |
          set -e
          git tag --list
          count=$(git tag --list | wc -l)
          if [ $count -ne 0 ]; then exit 1; fi
  integration-test-checkout_advanced_tags:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout_advanced:
          clone_options: "--depth 1"
          fetch_options: "--depth 1000"
      # should be all tags in fetch depth
      - run: |
          set -e
          git tag --list
          count=$(git tag --list | wc -l)
          if [ $count -eq 0 ]; then exit 1; fi
  integration-test-checkout_alpine:
    docker:
      - image: circleci/redis:alpine3.13
    steps:
      - run: apk update && apk add openssh git # openssh is required
      - git-shallow-clone/checkout
  integration-test-checkout_depth:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout:
          depth: 5
          fetch_depth: 10
  integration-test-checkout_fetchdepth:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout:
          fetch_depth: 1
  integration-test-checkout_keyscan_bitbucket:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout:
          keyscan_bitbucket: true
  integration-test-checkout_keyscan_github:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout:
          keyscan_github: true
  integration-test-checkout_macos:
    macos:
      xcode: 13.0.0
    steps:
      - git-shallow-clone/checkout
  integration-test-checkout_notags:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout:
          fetch_depth: 1000
          no_tags: true
      # should be no tags
      - run: |
          set -e
          git tag --list
          count=$(git tag --list | wc -l)
          if [ $count -ne 0 ]; then exit 1; fi
  integration-test-checkout_path:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout:
          path: src
  integration-test-checkout_tags:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout:
          fetch_depth: 1000
      # should be all tags in fetch depth
      - run: |
          set -e
          git tag --list
          count=$(git tag --list | wc -l)
          if [ $count -eq 0 ]; then exit 1; fi

workflows:
  # Prior to producing a development orb (which requires credentials) basic validation, linting, and even unit testing can be performed.
  # This workflow will run on every commit
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: guitarrapc/git-shallow-clone
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev

  # This `integration-test_deploy` workflow will only run
  # when the run-integration-tests pipeline parameter is set to true.
  # It is meant to be triggered by the "trigger-integration-tests-workflow"
  # job, and run tests on <your orb>@dev:${CIRCLE_SHA1:0:7}.
  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # your integration test jobs go here: essentially, run all your orb's
      # jobs and commands to ensure they behave as expected. or, run other
      # integration tests of your choosing
      # Run any integration tests defined within the `jobs` key.
      - integration-test-checkout
      - integration-test-checkout_advanced
      - integration-test-checkout_advanced_fetchoptions
      - integration-test-checkout_advanced_notags
      - integration-test-checkout_advanced_tags
      - integration-test-checkout_alpine
      - integration-test-checkout_depth
      - integration-test-checkout_fetchdepth
      - integration-test-checkout_keyscan_bitbucket
      - integration-test-checkout_keyscan_github
      - integration-test-checkout_macos
      - integration-test-checkout_notags
      - integration-test-checkout_path
      - integration-test-checkout_tags

      # Publish a semver version of the orb. relies on
      # the commit subject containing the text "[semver:patch|minor|major|skip]"
      # as that will determine whether a patch, minor or major
      # version will be published or if publishing should
      # be skipped.
      # e.g. [semver:patch] will cause a patch version to be published.
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: guitarrapc/git-shallow-clone
          add-pr-comment: false
          fail-if-semver-not-indicated: false
          publish-version-tag: true
          requires:
            - integration-test-checkout
            - integration-test-checkout_advanced
            - integration-test-checkout_advanced_fetchoptions
            - integration-test-checkout_advanced_notags
            - integration-test-checkout_advanced_tags
            - integration-test-checkout_alpine
            - integration-test-checkout_depth
            - integration-test-checkout_fetchdepth
            - integration-test-checkout_keyscan_bitbucket
            - integration-test-checkout_keyscan_github
            - integration-test-checkout_macos
            - integration-test-checkout_notags
            - integration-test-checkout_path
            - integration-test-checkout_tags
          filters:
            branches:
              only:
                - master
                - main
